# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 399b9fb514f183ed1461d0a489fedf0f5178c4247d28ae691bc892c31e6e58c7fc4e31f9561dcec8dd697be179e9cc115460af84b22fabdaf6a348485f7dcc5c

test:
  secret_key_base: 07a2110251f17a05773f1c51045cf001683e102d330c519dceb518a901f3f41813c45ce51034a69bda61e58c395c218ecff84bc11c8cb71d2b6842da98dd07a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
